"""add store verification helpers, review photo, ---

Revision ID: 0b9af3142144
Revises: 309cd5bec932
Create Date: 2026-09-04 18:16:58.799316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9af3142144'
down_revision = '309cd5bec932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
