"""add cover photo, saved payment, measurement unit, cart added_at

Revision ID: 555540e4ab5d
Revises: 0b9af3142144
Create Date: 2026-09-05 17:15:11.006860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555540e4ab5d'
down_revision = '0b9af3142144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('saved_shamcash_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('measurement_unit', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('measurement_unit')
        batch_op.drop_column('saved_shamcash_number')
        batch_op.drop_column('cover_path')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
